---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd daemon

- name: Restart pathfinder
  ansible.builtin.systemd:
    name: "{{ pathfinder_service_name }}"
    state: restarted
  listen: restart pathfinder
  when: pathfinder_service_state != 'stopped'
