---
- name: "Ulimits | Deploy limits configuration file"
  ansible.builtin.template:
    src: limits-starknet.conf.j2
    dest: /etc/security/limits.d/90-starknet-services.conf
    owner: root
    group: root
    mode: "0644"

- name: "Ulimits | Apply limits via pam_limits"
  community.general.pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop: "{{ base_ulimits }}"
  loop_control:
    label: "{{ item.domain }}:{{ item.limit_item }}:{{ item.limit_type }}"
